# Generated by Django 3.2.16 on 2023-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20230508_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='imge',
            field=models.ImageField(blank=True, upload_to='birthdays_images', verbose_name='Фото'),
        ),
    ]
